### ISSUE TITLE
배포, 인프라 구축 완료 후 탄력적 IP 제거

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#13]

**Comment by Hyeon9mak** [comment]
인터넷 연결에 필요한 작업이 끝난게 확인되면 amazon ec2 콘솔에 접속해서 탄력적 IP 제거만 수행하면 되므로, 

- 탄력적 IP 제거
- 제거 후 인터넷 연결이 제대로 끊어졌는지 확인

포함해서 총 10분 소요 예상

**Comment by Junroot** [comment]
추정시간: 30분

- 크게 어려움이 없어보임.

**Comment by lns13301** [comment]
10분

**Comment by unluckyjung** [comment]
딸칵질 10분내외

**Comment by Hyeon9mak** [comment]
## 결과
![image](https://user-images.githubusercontent.com/37354145/126984186-5d977c66-a1da-4403-9c30-2d4973c5d7fb.png)
![image](https://user-images.githubusercontent.com/37354145/126984191-154719d8-3611-4244-9b72-7bf26771122d.png)

![image](https://user-images.githubusercontent.com/37354145/126984432-e5620010-0bb6-4c9b-b8f0-c4b8df7ceb30.png)
![image](https://user-images.githubusercontent.com/37354145/126984496-a7eab330-7bdc-4281-b6a9-c44d70ea1233.png)

`EC2-babble-db`, `EC2-babble-was` 탄력적 IP 제거 후 인터넷 연결 끊김 확인 완료!

총 소요시간 10분!
