### ISSUE TITLE
유저 리스트가 id순으로 정렬되는 현상을 수정한다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse-teams/2021-babble#247]
호스트도 바뀌는 현상이 발생중.

**Comment by Hyeon9mak** [comment]
데이터베이스에서 유저 리스트를 꺼내 올 때 자동으로 id 순으로 정렬되는 것으로 예상됨.
생각나는 임시 해결 방편으로는 `입장 시각을 기록해서 정렬하기`인데, 이 방법 또한 호스트가 바뀔 위험이 존재함.

**Comment by unluckyjung** [comment]
- 논의하다보니 전체적인 재설계가 필요하다. (엔티티간 연관관계)
- 임시적으로는 get할시 정렬을 수행해서 해결하도록했다.
