### ISSUE TITLE
관리자 페이지에 관해 논의한다.

### ISSUE THREAD

**Issue by iborymagic** [woowacourse-teams/2021-babble#249]
게임과 태그를 긁어오지 않고, 직접 추가해주는 방식을 선택했으므로 관리자 페이지의 존재는 불가피할 것으로 보임니당
게임 추가/삭제 post 요청, 태그 추가/삭제 post 요청 정도가 추가적으로 요구될 듯 합니당
4차 데모데이까지 만들어보면 좋지 않을까염?
priority-2로 두겠슴당
헤헷

- [x] #311
- [x] #312

**Comment by unluckyjung** [comment]
2021-08-04(목) 오전중 다시추가적으로 논의할 예정
- 관리자 페이지 접근을 어떻게 제한할것인가?
