### ISSUE TITLE
Room-Session-User 연관관계 리팩토링

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse-teams/2021-babble#264]
![image](https://user-images.githubusercontent.com/37354145/127630763-8738f3ee-4bb1-4071-9b4b-559efea1227b.png)

**Comment by Junroot** [comment]
사진으로 이해가 잘안돼요. 글로 좀 더 명확하게 설명해주세요.

**Comment by Hyeon9mak** [comment]
안돼요!

**Comment by lns13301** [comment]
난 누뚜뼌!
