### ISSUE TITLE
문자열 길이가 긴 메시지를 보내면 말풍선을 벗어나는 버그를 해결한다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse-teams/2021-babble#276]
## 버그 현상
![image](https://user-images.githubusercontent.com/43930419/127778218-66d07afa-7527-4551-b5fc-7e706f1fa546.png)

![image](https://user-images.githubusercontent.com/43930419/127778250-bd9c3753-a16e-4e27-b822-7cf004cb8d47.png)

## 한국어는 괜찮다.
![image](https://user-images.githubusercontent.com/43930419/127778221-9a6e3850-bc04-4aba-8355-b8226a563f28.png)

**Comment by iborymagic** [comment]
해결함 ㅋ
