### ISSUE TITLE
입장 중인 방을 연타하면 닉네임이 복사되는 버그

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#287]
![image](https://user-images.githubusercontent.com/4648244/127841400-dd606558-c36a-4d2a-8a6d-8c458af467ec.png)

**Comment by unluckyjung** [comment]
백엔드 서버측에서는 다른 id로 참여되는것을 확인.
프론트쪽에서의  추가작업이 필요할것으로 추측되어짐
