### ISSUE TITLE
배포 인프라 파이프라이닝을 구축한다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse-teams/2021-babble#3]

**Comment by Hyeon9mak** [comment]
## WebServer - WAS - DB - Bastion 도식화
![image](https://user-images.githubusercontent.com/37354145/125563507-4bddd38a-c6c3-4895-9437-e601897da96e.png)

https://github.com/Hyeon9mak/WIL/blob/main/infrastructure/reverse-proxy-was-mysql.md

**Comment by Hyeon9mak** [comment]
## CloudFront - S3 액세스 이슈 해결
- CloudFront에 S3 bucket을 등록하더라도, S3에서는 단순한 public access 로 판단한다.
    - S3 public access를 모두 막아두었다면 접근이 불가능하다.
- CloudFront OAI를 발급하고 사용하도록 설정, S3 측에도 보안 정책으로 CloudFront OAI 키값을 등록해준다.

https://github.com/Hyeon9mak/WIL/blob/main/infrastructure/access-s3-through-cloudfront.md

**Comment by Junroot** [comment]
## Github Action을 위한 CI/CD 도입 도식화

![image](https://user-images.githubusercontent.com/4648244/125721279-fabf57c7-99ef-4010-b900-67621f108361.png)

**Comment by Hyeon9mak** [comment]
- 데이터베이스를 도커 위에 올릴지 말지
- 올린다면 기존 데이터를 어떻게 할 것인지

결정만 된다면 이미 Test 인스턴스에서 데이터베이스를 올려봤기 때문에 30분내로도 해결 할 수 있을 것 같음

**Comment by Junroot** [comment]
추정 시간: 1시간

> 추정 시간: 1시간
> 
> 기존 데이터가 더미 데이터이므로 지워도 문제없을거로 추정

https://github.com/woowacourse-teams/2021-babble/issues/76#issuecomment-883065372

- 도커 위에 올려도 문제 없다고 판단.

**Comment by unluckyjung** [comment]
## 추정시간 1시간 내외
- 저는 이미 완료된 부분이라고 생각하는데, 토의가 필요해보이시면 따라감

**Comment by Hyeon9mak** [comment]
## 결론
30~60분 내로 끝날 것으로 예상됨

**Comment by Hyeon9mak** [comment]
## 완료
- 총 수행 시간: 2시간 (08:00~10:00)
  - 학습시간: 90분
  - 적용시간: 30분

적용 자체는 큰 어려움이 없었으나, 한글 인코딩 문제 관련해서 추가 설정이 필요했음을 뒤늦게 파악함.
예상시간보다 1시간 더 소요되었다.

https://github.com/Hyeon9mak/WIL/blob/main/database/migrate-local-database-to-docker.md
