### ISSUE TITLE
깃허브 소개 페이지 내용을 변경한다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse-teams/2021-babble#30]
기술스택의 변화가 있는 부분을 수정한다.

**Comment by Hyeon9mak** [comment]
- (기술스택 추가, 제거에 따라 바뀔 수 있으나) 30분 내로 끝날거 같음.
  - README.md 업데이트가 귀찮아서 안하는거지 어려워서 안하는건 아니니까...

**Comment by Junroot** [comment]
추정 시간: 30분

- 크게 어려움이 없어보임.

**Comment by unluckyjung** [comment]
## 추정시간 : 30분내외
- 그냥 한명이 주도해서 화면 공유하며 진행하면 해결될 부분으로 추정
