### ISSUE TITLE
EC2, nginx, spring boot, DB 서버 시간 맞추기

### ISSUE THREAD

**Issue by iborymagic** [woowacourse-teams/2021-babble#300]
EC2, nginx, spring boot, DB 서버 시간 맞추기 ㅋㅋㄹㅃㅃ

**Comment by Hyeon9mak** [comment]
### EC2
```
$ sudo rm /etc/localtime 
$ sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime
```
위 설정을 진행하면 재부팅 후에도 운영체제 시간이 변경되어 있음을 확인함.

- [x] web-server
- [x] bastion
- [x] db
- [x] was
- [x] ci-cd
- [x] test
- [x] sonarqube

### NGINX
`docker-compose.yml` 파일에 환경변수-타임존 설정을 추가하면 해결 가능했음.

- [x] web-server
- [x] test

### DB
`docker-compose.yml` 파일에 환경변수-타임존 설정을 추가하면 해결 가능했음.

- [x] db
- [x] test

### WAS
`Dockerfile`에 빌드시 명령어 `-Duser.timezone=Asia/Seoul` 설정을 추가함
- [x] was
- [x] test

### S3, cloudfront
기본적으로 맞춰져 있는 것 같아 별도 설정을 진행하지 않음.

### 소나큐브
기본적으로 맞춰져 있는 것 같아 별도 설정을 진행하지 않음.
