### ISSUE TITLE
웹 소켓 관련 REST docs 명세 추가

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#36]

**Comment by Hyeon9mak** [comment]
- '자동화 라이브러리가 제공되는가'를 명확히 알고 싶다.
- 자동화 라이브러리가 제공되지 않더라도, 크게 명세할 부분이 많지 않을 것 같음.
  - 직접 명세서를 작성해보는 것도 괜찮은 경험이 될 것 같다.
 
명세 문서를 기존 REST API에 맞춰서 작성하면, 학습시간 포함 2~3시간 정도 소요되지 않을까?

**Comment by lns13301** [comment]
직접 명세서를 작성한다면 2시간 (+ 30분)
자동화 툴을 조사해보고 적용 혹은 직접 명세를 구현한다면 6시간 (+ 2시간)

**Comment by Junroot** [comment]
> 추정 시간: 5시간
> 
> - 웹 소켓을 수동으로 문서화해야된다면 2시간
> - 웹 소켓 자동 문서화가 가능하다면 5시간

https://github.com/woowacourse-teams/2021-babble/issues/79#issuecomment-883062855

**Comment by Hyeon9mak** [comment]
## 결론
넉넉잡아 2시간 걸릴 것으로 예상됨
