### ISSUE TITLE
sonarqube nginx 적용 방법 논의

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#365]
# sonarqube nginx 적용 방법 논의

## 1안: 기존 web-server의 nginx에 sonarqube 연결
![image](https://user-images.githubusercontent.com/37354145/128594214-f06911a9-f0c3-41d9-8d54-2f73501de80c.png)

## 2안: sonarqube ec2에 도커로 별도의 nginx 구성하기
![image](https://user-images.githubusercontent.com/37354145/128594243-3678ccdd-17ca-40df-b646-859e17572153.png)

**Comment by Hyeon9mak** [comment]
## 결론 - 1안 도입
누가, 언제 진행할지는 추후 결정
