### ISSUE TITLE
babble.gg 도메인에 www 가 포함되는 것 논의

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse-teams/2021-babble#366]
op.gg, naver.com, google.com 등 모두 www 로 강제 리다이렉팅 시키고 있다.

`op.gg` -> `www.op.gg`
`naver.com` -> `www.naver.com`
`google.com` -> `www.google.com`

이에 따라 우리 팀도 `babble.gg` -> `www.babble.gg`로 리다이렉팅 할 것인지,
그대로 둘 것인지,
`www.babble.gg` -> `babble.gg` 반대 방향으로 리다이렉팅 할 것인지 회의를 진행한다.

**Comment by unluckyjung** [comment]
## 결론
- https://www.notion.so/www-babble-gg-vs-babble-gg-d1a9b51205b047189ccd6fb95c9dd3dc

[www.babble.gg](http://www.babble.gg) → babble.gg 리다이렉트

[babble.gg](http://babble.gg) → babble.gg  , [www.babble.gg](http://www.babble.gg) → babble.gg
