### ISSUE TITLE
WAS, DB 탄력적 IP 제거

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse-teams/2021-babble#367]
WAS 쪽 CloudWatch로그 수집을 위해서 일시적으로 탄력적 IP를 부여 후 회수하지 않은 듯 해보인다.
만일 탄력적 IP 회수 후에도 정상적으로 로그 수집이 된다면 탄력적 IP를 제거하고,
로그 수집이 진행되지 않는다면 탄력적 IP를 영구적으로 부여하자.

**Comment by lns13301** [comment]
퍼블릭 IP 가 없으면 데이터를 수신하지 못한다. 즉, 탄력적 IP 가 존재해야지 Log 나 메모리 사용률 등의 정보를 주고 받을 수 있다.
