### ISSUE TITLE
백엔드 코드 리팩토링

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#37]
- [x] https://github.com/woowacourse-teams/2021-babble/issues/75
- [x] #144

**Comment by unluckyjung** [comment]
- 4시간내외
  - 리팩토링 할 시간을 딱 정해서 가지기 보다는, 주기적으로 develop에서 feature로 떼어간뒤 pr을 보내고 서로 리뷰하는 식으로 진행했으면 어떨까함
  - 4시간은 대충 적었을뿐 이시간을 딱 정해 진행하자는 의미가 X

**Comment by Hyeon9mak** [comment]
- 10시 출근 18시 퇴근 기준 2일 소요 예상
  - 1차적인 리팩토링, PR을 쏘고 서로 리뷰 주고 받기, 리뷰 반영하기 단계를 거치면 2일 이상 소요될거 같다.

**Comment by lns13301** [comment]
지금까지 구현한 코드에 대한 리팩토링에 대해서만 리뷰를 주고받는 형식으로 진행하면 8시간 소모될 것으로 보인다.

**Comment by Junroot** [comment]
예상 시간: 6시간

- 2차데모까지 구현한 코드를 기준으로 정의.
- JPA에대한 학습을 병행해야하므로 어느 정도 시간이 필요할 것으로 보임.

**Comment by Hyeon9mak** [comment]
## 결론 - 추가 논의 필요
1. 리팩토링 기간을 별도로 생각하고, 각자 생각드는 방식대로 커밋 후 PR을 쏴서 서로 리뷰해보는 건 어떨까?
2. 리팩토링 할 부분이 보이는대로 계속 리팩토링을 해야할텐데 (지속적으로) 굳이 날짜를 분리할 필요가 있을까? 짧게 짧게 리팩토링을 진행하자.

추후 논의 예정

```
- 더미 데이터가 매번 추가되는 이슈
- 예외에 적절한 http 코드로 응답하지 못하고 있는 이슈
- List로 작성된 필드 일급 컬렉션으로 변경하기 이슈
- `getHost()`, `getGuests()` 메서드 예외처리 이슈
```

기타 더 추가될 수도 있으나, 당장은 뽑힌 내용은 위와 같다.

**Comment by unluckyjung** [comment]
# 결론 


```
## 예상 시간 : 4시간

- 더미 데이터가 매번 추가되는 이슈
- 예외에 적절한 http 코드로 응답하지 못하고 있는 이슈
- List로 작성된 필드 일급 컬렉션으로 변경하기 이슈
- `getHost()`, `getGuests()` 메서드 예외처리 이슈
```

> 21.07.21.19:44

- @Junroot 가 맡아서 진행
- 나머지 인원 @Hyeon9mak @unluckyjung @lns13301 는 리뷰어 역할 수행.

- 같은 코드를 동시에 리팩토링하는것을 지양하므로, 한명이 맡아서 수정하는것으로 결론
