### ISSUE TITLE
백엔드 서버 성능 측정

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#538]
백엔드 서버 성능 측정을 한 뒤, 개선을 위해 어떤 작업을 할 수 있을지 검토해본다.

**Comment by Junroot** [comment]
smoke test:
[recordedsimulation-20211008085057426.zip](https://github.com/woowacourse-teams/2021-babble/files/7310423/recordedsimulation-20211008085057426.zip)

load test: 
[recordedsimulation-20211008095937814.zip](https://github.com/woowacourse-teams/2021-babble/files/7310415/recordedsimulation-20211008095937814.zip)

**Comment by Hyeon9mak** [comment]
## Smoke
![image](https://user-images.githubusercontent.com/37354145/140594721-f95bd09a-4f23-4680-acef-939e092f32a2.png)

[recordedsimulation-20211106020953106.zip](https://github.com/woowacourse-teams/2021-babble/files/7489634/recordedsimulation-20211106020953106.zip)

<br>
## Load
![image](https://user-images.githubusercontent.com/37354145/140594762-6ff26e60-7eb1-4d1a-a1cd-895e1184b3cb.png)

[recordedsimulation-20211106021956870.zip](https://github.com/woowacourse-teams/2021-babble/files/7489635/recordedsimulation-20211106021956870.zip)

**Comment by lns13301** [comment]
N + 1, BatchSize 조절 후

## Smoke

![image](https://user-images.githubusercontent.com/49058669/140887665-14d049c3-1a37-4b2e-95ce-80c0ca625b34.png)

## Load

![image](https://user-images.githubusercontent.com/49058669/140887787-e6570e28-eb39-4335-9453-948ad33affd2.png)
