### ISSUE TITLE
테스트 ec2와 프로덕션 ec2가 s3에 접근 권한이 없는 문제 해결

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#559]

**Comment by unluckyjung** [comment]
https://aws.amazon.com/ko/premiumsupport/knowledge-center/attach-replace-ec2-instance-profile/

이걸 보긴했는데 aws cli도 필요하고, 좀더 찾아봐야겠더라구요.

**Comment by Junroot** [comment]
# EC2가 S3에 접근하지 못하는 문제

![image](https://user-images.githubusercontent.com/4648244/135566662-c1e1bdc4-ac44-4fde-93d0-4af79598c91c.png)

EC2에 IAM을 제대로 부여해뒀는지 확인해보자...

![image](https://user-images.githubusercontent.com/4648244/135566670-cb9ec6e9-6768-453b-8664-9d892b74f6d6.png)

내가 전에 정리해두고 이걸 또 까먹었네...
