### ISSUE TITLE
불필요한 static file 제거

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse-teams/2021-babble#70]
브라우저를 통해 API 서버 직접 접속시 불필요한(테스트를 위해 준비했던) 페이지가 로드 됨

**Comment by unluckyjung** [comment]
- 5분내외
  - 필요성에 대해서 논의를 해보고, 바로 삭제를 진행해도 된다고 생각

**Comment by Hyeon9mak** [comment]
5분
포츈 말에 동의!

**Comment by Junroot** [comment]
추정 시간: 30분

- 구현이 빠르지만, 의견 충돌이 있을 것을 고려해 여유롭게 할당.

**Comment by unluckyjung** [comment]
전혀 불필요하지 않음!!!!!
