### ISSUE TITLE
서비스 이전을 위한 프로젝트 백업 진행

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse-teams/2021-babble#744]
- [x] 데이터베이스
- [x] 백엔드 개발 코드
- [x] Web Server 설정 파일
- [x] 프론트엔드 개발 코드
- [x] CICD yml 파일
- [x] WAS 도커 설정 파일
  - [x] 도커스웜(Redis) 설정 내용

---

추가 될 내용 있으면 추가 바람~

**Comment by unluckyjung** [comment]
소나큐브 설정 파일도 옮겨야 하지 않을까 싶네요.
이후 더 생각나는거 있으면 코멘트 이어 달겠습니다.

**Comment by Hyeon9mak** [comment]
## 완료
- db
  - SQL 덤프 파일 백업
- test-db
  - 유의미한 데이터는 프로덕션 DB쪽에 있으므로 백업 생략
- db-slave1
- db-slave2
- test-db-slave1
- test-db-slave2
  - 별도로 옮길 파일 없음
- ngrinder-agent
  - 별도로 옮길 파일 없음
  - 복구를 원한다면 ngrinder 공식 문서를 다시 참고하면 됨
- ngrinder-controller
  - 별도로 옮길 파일 없음
  - 복구를 원한다면 ngrinder 공식 문서를 다시 참고하면 됨
- test-web-server
  - `Dockerfile`, `docker-compose.yml`, `nginx.conf` 백업
- sonarqube
  - `docker-compose.yml` 백업
- cicd
  - 레퍼지토리 워커를 생성할 때 설정을 따르면 되므로 백업 생략
- web-server
  - `Dockerfile`, `awslogs-agent-setup.py`, `docker-compose.yml`, `nginx.conf` 백업

<br>

## 다시 확인이 필요한 부분
- test-was-worker1
- test-was-worker2
- test-was-manager
- was-logs
- was-worker1
- was-worker2
- was-manager
- junit-db
- junit-redis
  - 루트 의견 필요!!
- redis
- test-redis
  - 로컬과 도커에 아무것도 안보임
  - 어떤 용도로 생성된 EC2인지 다시 한 번 체크가 필요함
