### ISSUE TITLE
예외 발생시 적절한 http status code로 응답하도록 수정

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#75]

**Comment by unluckyjung** [comment]
- 1시간
  - 현재 응답할 상태코드 정하기 + 예외발생에 대한 처리에 대한 일이 하나로 묶여있음.
  - 상태코드를 선정하는데 시간이 할애되기보다는, 발생할 수 있는 예외발생에 대한 처리에 시간이 더 할애될것으로 보임
  - https://github.com/woowacourse-teams/2021-babble/issues/37#issuecomment-883051962 코멘트 부분을 확인하길 권장

**Comment by Hyeon9mak** [comment]
- 1~2시간
  - 응답코드 선정에 프론트 백이 서로 합이 맞는다면 빠르게 끝날 것 같다.
  - 다만 엑셀 파일에 작성했던 기능 명세 등을 보면서 예외상황을 '예측' 해야 하므로, 시간이 더 걸릴 수도 있을 것 같다.

**Comment by Junroot** [comment]
추정 시간: 2시간

- 백과 프론트가 어느 정도 이야기할 필요가 있다고 생각함.
- 구현 자체는 빠르게 될것으로 추정.

**Comment by unluckyjung** [comment]
# 완료시간
- #140 합쳐서 1시간 소모
