### ISSUE TITLE
WAS 서버와 데이터베이스를 도커 위에서 동작하도록 마이그레이션 한다.

### ISSUE THREAD

**Issue by Hyeon9mak** [woowacourse-teams/2021-babble#76]

**Comment by Hyeon9mak** [comment]
### WAS 마이그레이션 완료

![image](https://user-images.githubusercontent.com/37354145/126156738-2dd26202-a356-47bf-a3ae-e0750d4942a5.png)
![image](https://user-images.githubusercontent.com/37354145/126156757-62392d36-184d-4bb6-9b48-3c7de8f181e6.png)

**Comment by Hyeon9mak** [comment]
데이터베이스 마이그레이션에 대해서는 좋은 아티클들이 많이 있으나, 아티클 내용을 오해할 소지가 있는거 같아 같이 진행했으면 좋겠어유
- https://joont92.github.io/docker/volume-container-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0/
- https://happygrammer.github.io/docker/mariadb/

1. `-v` 옵션을 주지 않더라도 데이터가 알아서 저장된다는 건지, -v 옵션을 주지 않으면 데이터가 컨테이너가 저장되었다가 파기된다는 건지 정확하게 이해가 안됨
2. 현재 데이터베이스에 등록된 더미데이터를 날려도 되는지 프론트/백 모두와 이야기를 나눠봐야할 것 같음

**Comment by Hyeon9mak** [comment]
- 데이터베이스를 도커 위에 올릴지 말지
- 올린다면 기존 데이터를 어떻게 할 것인지
결정만 된다면 이미 Test 인스턴스에서 데이터베이스를 올려봤기 때문에 30분내로도 해결 할 수 있을 것 같음

**Comment by Junroot** [comment]
추정 시간: 1시간

- 기존 데이터가 더미 데이터이므로 지워도 문제없을거로 추정

**Comment by lns13301** [comment]
2시간
- 기존 데이터를 데이터 마이닝 해보는 것도 해보면 좋을듯

**Comment by unluckyjung** [comment]
## 추정시간 (2시간)
- 단순히 적용하기보다, 왜 이렇게 했는지에 대한 문서화 기록이 필요해보임
- 문서화 시간에 1시간 30분이상이 들어갈것으로 추정

**Comment by unluckyjung** [comment]
# 결론 


```
## 예상 시간 - 2시간

- 더미데이터는 삭제되어도 크게 상관없다 결론. 
- 살릴수 있으면 살려보는쪽으로
```

> 21.07.21.19:51

- @Hyeon9mak 이 맡아서 진행
- 문서화 한뒤 공유하는것으로 결론

**Comment by Hyeon9mak** [comment]
## 완료
- 총 수행 시간: 2시간 (08:00~10:00)
  - 학습시간: 90분
  - 적용시간: 30분

적용 자체는 큰 어려움이 없었으나, 한글 인코딩 문제 관련해서 추가 설정이 필요했음을 뒤늦게 파악함.
예상시간보다 1시간 더 소요되었다.

https://github.com/Hyeon9mak/WIL/blob/main/database/migrate-local-database-to-docker.md
