### ISSUE TITLE
AWS로 이전한다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse-teams/2021-babble#81]
- [ ] #7 
- [ ] #83

**Comment by iborymagic** [comment]
배포 소요 예정 시간: 넉넉잡아 하루 다 쓸 예정.

**Comment by Hyeon9mak** [comment]
## 결론
백/프론트 일정이 괜찮은 날 오전에 S3 / Cloudfront 개설 다 같이 진행하고,
오후에 프론트가 직접 서버 배포하는 걸로

**Comment by ddongule** [comment]
13:20 - 14:00 프론트엔드 S3 배포 연습
15:08 - 15:14 프론트엔드 S3 수동 배포 
15:30 - 18:00 프론트엔드 배포 자동화 완료 

총 3시간 16분
