### ISSUE TITLE
디버깅할 수 있는 로그 파일 출력

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse-teams/2021-babble#84]
- [x] #91
- [x] #92
- [x] #93

**Comment by Hyeon9mak** [comment]
#91 -> 1시간
#92 -> 2시간
#92 -> 1시간
총 4시간 예상

**Comment by Junroot** [comment]
> 추정 시간: 1시간
> 
> 로깅 대상이 많지 않아 오래걸리지 않을 것으로 추정

https://github.com/woowacourse-teams/2021-babble/issues/91#issuecomment-883055689

> 추정 시간: 2시간
> 
> 로딩 레벨에 대한 이해 필요.(학습에 1시간+)
> 로딩 레벨 선정은 아직 로깅 대상이 적기 때문에 빠르게 끝날 것으로 추정.(30분)

https://github.com/woowacourse-teams/2021-babble/issues/92#issuecomment-883056536

>추정 시간: 5시간
> 
> CloudWatch로 로깅 수집까지한다면 5시간
> 단순히 파일로만 로깅한다면 3시간

https://github.com/woowacourse-teams/2021-babble/issues/93#issuecomment-883058221

최종 추정 시간: 8시간

**Comment by lns13301** [comment]
로깅 대상을 선정한다. 1시간
로깅 레벨을 선정한다. 1.5시간
로깅을 구현한다. 3시간
