### ISSUE TITLE
자동화 테스트 코드를 추가한다.

### ISSUE THREAD

**Issue by unluckyjung** [woowacourse-teams/2021-babble#87]
- [x] #162

**Comment by lns13301** [comment]
구현과 함께 진행하기 때문에 시간을 산출하기 어려워 보인다.

**Comment by Hyeon9mak** [comment]
와일더 말대로 언제 어디서 막힐지 몰라서... 시간 산출이 어렵다.
자동화 테스트 코드를 우선시 하는것도 좋아보인다. 
현재 규모에서도 시간 산출이 어려울정도로 막막하게 느껴지는데, 기능 추가가 더해지면 겉잡을 수 없을 것 같다.

현업에서 왜 테스트 코드 작성을 포기하는지 살살 느껴진다...

**Comment by Junroot** [comment]
추정 시간: 0시간

TDD로 진행하고 있기 때문에 따로 고려할 필요없어보인다.

**Comment by iborymagic** [comment]
- 지금까지 구현한 코드의 테스트 코드 작성: 6시간
(E2E테스트 코드는 보통 사용자가 페이지에 접속한 후부터 유저 플로우에 따라 맞닥뜨릴 수 있는 모든 상황들에 대해 테스트 케이스를 작성하기 때문에 시간이 매우 오래 걸림.)
- 앞으로의 테스트 코드 구현: 시간 산출 어려움.
TDD로 진행하기에는 시간이 너무 오래걸릴 것 같아, 구현을 끝낸 후에 리팩토링에 사용할 목적으로 테스트 코드를 구현하지 않을까 싶음.
