### ISSUE TITLE
로깅 대상을 선정한다.

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#91]

**Comment by lns13301** [comment]
논의 시간 : 60분 (+ 30분)
아직 비즈니스 로직이 많지 않고, 또한 구현해야할 부분을 고려했을 때에도 많은 양이 아니기 때문에 이 정도 시간을 측정했다.

**Comment by unluckyjung** [comment]
### 추정시간 : 1시간 내외
- **로깅 대상** 자체를 선정하는데에는 큰 시간이 걸리지 않을것으로 추정되어짐.

**Comment by Hyeon9mak** [comment]
나도 와일더, 포츈 의견에 동의. 로깅 대상 자체가 그리 많지 않아서 회의가 오래 걸리거 같진 않음.

**Comment by Junroot** [comment]
추정 시간: 1시간

로깅 대상이 많지 않아 오래걸리지 않을 것으로 추정

**Comment by Junroot** [comment]
> 추정 시간: 1시간
> 
> 로깅 대상이 많지 않아 오래걸리지 않을 것으로 추정

**Comment by Hyeon9mak** [comment]
## 결론
1시간

**Comment by unluckyjung** [comment]
## WAS
예외
컨트롤러 (요청,응답)
인터셉터
DB SQL문 로깅

## 인프라
nginx 에 대한 요청, 응답
요청한 클라이언트의 ip


- 추가적으로 로깅이 더 필요해보이는 경우 차후 추가

---

13:47 ~ 14:07

`20분 / 1시간`

**Comment by Hyeon9mak** [comment]
## WAS
예외 - ExceptionHandler(Advice)
컨트롤러 요청, 응답 - Filter 또는 Interceptor
DB SQL 문 로깅 - application.properties

## 인프라
nginx - https://extrememanual.net/10139

**Comment by unluckyjung** [comment]
![image](https://user-images.githubusercontent.com/43930419/126945697-35c2acae-e6c2-4b39-b79c-c477f647172d.png)

---

- 서버 컴퓨팅적인 정보들
  - `cloudWatch` 로 붙이기
