### ISSUE TITLE
SLF4J 로깅 레벨을 선정한다.

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#92]

**Comment by lns13301** [comment]
논의 시간 : 90분 (+ 30분)
아직 비즈니스 로직이 많지 않고, 또한 구현해야할 부분을 고려했을 때에도 많은 양이 아니기 때문에 이 정도 시간을 측정했다.

**Comment by Hyeon9mak** [comment]
2시간 소요 예상.
로깅 레벨에 대해서 명확하게 공부하는 시간과, 현업에서 로깅 레벨을 어떻게 선정하는지 조사하는 필요할 것 같다.
공부한 내용과 조사 내용을 토대로 로깅 레벨을 선정하는데 총 2시간 정도 소요될 것 같음.

**Comment by unluckyjung** [comment]
### 추정시간 : 2시간 내외
- 로깅 레벨에 대한 개념 학습 30분 내외
- 각 상황에 따른 로깅 레벨을 어떻게 책정할지에 대한 토의시간이 1시간 내외로 소모될것으로 예상
- 아직 로깅에 대한 이해가 없어서 나이브하게 시간 산출

**Comment by Junroot** [comment]
추정 시간: 2시간
- 로딩 레벨에 대한 이해 필요.(학습에 1시간+)
- 로딩 레벨 선정은 아직 로깅 대상이 적기 때문에 빠르게 끝날 것으로 추정.(30분)

**Comment by Hyeon9mak** [comment]
## 결론
2시간

**Comment by unluckyjung** [comment]
# 결론

- 자다가 뛰어나가야하면 , 
  - FATAL : 아주 심각한 에러가 발생한 상태, 시스템적으로 심각한 문제가 발생해서 어플리케이션 작동이 불가능할 경우
  - 당장 서비스를 내려야 하는 정도의 에러 (ex : 결제시스템)

- 자고일어나서 바로 수정할 사안이면
  - ERROR : 요청을 처리하는 중 문제가 발생한 경우

- 그대로 자고 있어도 되면
  - WARN : 처리 가능한 문제, 향후 시스템 에러의 원인이 될 수 있는 경고성 메시지를 나타냄

- INFO : 상태변경과 같은 정보성 메시지를 나타냄

- DEBUG : 프로그램을 디버깅하기 위한 정보 지정
  - DB SQL문

---

```java
// TODO : LOGGER[WARNING]
@ExceptionHandler(Exception.class)
public ResponseEntity<ExceptionDto> unexpectedException() {
    return ResponseEntity.badRequest().body(new ExceptionDto("unexpected exception"));
}

// TODO : LOGGER[WARNING]
@ExceptionHandler(RuntimeException.class)
public ResponseEntity<ExceptionDto> unexpectedRuntimeException() {
    return ResponseEntity.badRequest().body(new ExceptionDto("unexpected runtime exception"));
}
```

- 예상치 못한 경우는 `WARNING`

```java
// TODO : LOGGER[INFO]
@ExceptionHandler(BabbleException.class)
public ResponseEntity<ExceptionDto> babbleException(final BabbleException babbleException) {
    return ResponseEntity.status(babbleException.status()).body(new ExceptionDto(babbleException.getMessage()));
}
```

- 예상된 경우 `INFO`

**Comment by lns13301** [comment]
Logback 을 사용하기 때문에 경고 수준을 한 단계씩 미룸

자다가 뛰어나가야하면 ,

ERROR : 아주 심각한 에러가 발생한 상태, 시스템적으로 심각한 문제가 발생해서 어플리케이션 작동이 불가능할 경우
당장 서비스를 내려야 하는 정도의 에러 (ex : 결제시스템)

WARN : 자고일어나서 바로 수정할 사안

INFO : 처리 가능한 문제, 향후 시스템 에러의 원인이 될 수 있는 경고성 메시지를 나타냄
