### ISSUE TITLE
로깅을 구현한다.

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#93]

**Comment by Hyeon9mak** [comment]
1시간 내외?
- 구현 자체는 로그백 등의 라이브러리가 워낙 강력하기 때문에 크게 어렵지 않을 것 같다.
- 오히려 로그 파일을 어떻게 관리할지 고민하는게 관건일듯

**Comment by unluckyjung** [comment]
### 추정시간 : 2시간 내외
- 도큐먼트 이해, 따라서 하는시간 (30시간)
- 로그파일을 어디에 저장힐지에 대한 고민 (30분)
- 로그가 필요한 부분에 구현?(1시간)
- 로깅을 해본경험이 없어서 나이브하게 시간 산출

**Comment by lns13301** [comment]
구현 시간 : 3시간 (+1시간)
- 로그 적용에는 큰 어려움이 없어보인다.
- 관리를 어떻게 할 지에 대해서 토의하면서 시간을 다소 소비할 것으로 보인다.
- 처음 시도해보는 내용이라서 알 수 없는 난간을 맞이할 수 있다.

**Comment by Junroot** [comment]
추정 시간: 5시간
- CloudWatch로 로깅 수집까지한다면 5시간
- 단순히 파일로만 로깅한다면 3시간

**Comment by Hyeon9mak** [comment]
## 결론
우선 로그파일을 만드는것 까지만 - 2~3시간 예상
추후 GA/CloudWatch 도입시 - 5~6시간 예상

- 로그파일만 만드는가, GA/CloudWatch 까지 도입하는건가?
- 우선 순위를 로그파일만 두고, 추후에 GA/CloudWatch를 추가 도입하는걸 고려해보자.

**Comment by unluckyjung** [comment]
## Logging을 어디까지 할것인지

- 로컬에서는 로깅파일이 필요한지?
- 테스트에서는 WARNING 까지볼것인지?
- 실제 배포되는 프로덕션에서는 어디까지 볼것인지?
