### ISSUE TITLE
3차 데모데이까지 구현할 기능들의 API명세를 정하고 구현한다.

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#94]
- [x] #96
- [x] #95
- [x] #167
- [x] #168
- [x] #169

**Comment by Junroot** [comment]
- API 설계: < 3시간. api하나당 40분 정도 걸릴 것으로 추정.
  - 방 목록: GET
  - 방 별 태그 목록: GET
  - 닉네임: POST
  - 방: POST (API 수정 필요. 인원 추가해야됨)
- API 구현: 6시간. API 하나당 넉넉하게 1.5시간

**Comment by iborymagic** [comment]
- 방 목록 페이지: 17시간 30분
- 방 생성 페이지: 10시간

**Comment by Hyeon9mak** [comment]
방 목록 페이지: 6시간
방 생성 페이지: 3시간

총 9시간

**Comment by Hyeon9mak** [comment]
## 결론
API 명세에 2 + 6 = 8 시간 소요 될 것으로 보인다.

전체 완성에는
프론트 - 나흘 정도 소요될 것으로 보인다. (그랬으면 좋겠다)
백 - 이틀 정도 소요될 것으로 보인다.

**Comment by Hyeon9mak** [comment]
## 중간점검
실제 3시간 정도에 80% 이상의 명세가 결정되었다.
웹소켓 관련 명세에서 고민이 많아진 덕분에 회의가 계속 이어지고 있다.

API 명세에 8시간이 소요될 것으로 예상했는데, 나머지 5시간 동안 
웹소켓 관련 명세에 집중 할 수 있을 것 같다.
