### ISSUE TITLE
방 생성 페이지

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#95]
- [x] 방 생성 페이지 디자인 확정짓기

- [x] 방 생성 페이지 컴포넌트 마크업을 진행한다.
- [x] #199
- [x] 자동완성 태그 검색 기능을 구현한다. #220 
  - 자동완성에 필요한 태그 목록 데이터
  - 방 목록 페이지와 동일한 기능이므로, 동일한 컴포넌트 재사용 예정
  - 태그 자동완성을 선택하면 해당 태그가 렌더링되는 기능
- [x] 선택한 태그를 취소하는 기능을 구현한다. #220 
  - 선택한 태그를 취소할 수 있는 기능
- [x] #221  
  - 방 생성 API를 활용해서 방을 생성한다.
- [x] 방 생성 취소하기 기능을 구현한다.
  - 방 생성 페이지가 닫히도록 구현한다.
- [x] 배경 이미지 불러오기

**Comment by Junroot** [comment]
> * API 설계: < 3시간. api하나당 40분 정도 걸릴 것으로 추정.
>   
>   * 방 목록: GET
>   * 방 별 태그 목록: GET
>   * 닉네임: POST
>   * 방: POST (API 수정 필요. 인원 추가해야됨)
> * API 구현: 6시간. API 하나당 넉넉하게 1.5시간
> * UX 디자인 및 마크업은 프론트의 의견에 �따름.

https://github.com/woowacourse-teams/2021-babble/issues/94#issuecomment-883053824

**Comment by iborymagic** [comment]
- 방 생성 페이지 디자인 확정짓기: 1시간
- 방 생성 페이지 컴포넌트 마크업: 2시간
- 방 생성 페이지 마크업: 3시간
- 자동완성 태그 검색 기능: 방 목록 페이지와 동일(재사용)
- 태그 삭제 기능: 1시간
- 방 생성 기능: 2시간
- 방 생성 취소하기: 1시간

**Comment by Hyeon9mak** [comment]
API 설계: 1시간. 크게 신경쓸 설계는 없어보임.
API 구현: (테스트코드 작성 포함) 2시간 예상.

총 3시간

**Comment by unluckyjung** [comment]
![image](https://user-images.githubusercontent.com/43930419/126265700-ae88545d-b5be-4e2d-9456-708afcb50fc3.png)
지금 피그마는 이런 형태지만, 방 생성할때 태그 선택도 해야하므로 

태그 목록을 불러오는 API 설계가 추가적으로 요구되어짐.

정리하면
- 태그 목록 불러오기 API (GET)
- 방 생성 (구현완료)

태그 목록 불러오기에 대한 API 만 추가되면 될것 같음.

## 예상시간 2시간내외
- API 설계 (30분)
- 구현 (1시간 ~ 1시간 30분)

**Comment by Hyeon9mak** [comment]
## 결론
설계 - 1시간
구현 - 1시간

2시간 정도 소요될 것 같음
