### ISSUE TITLE
방 목록 페이지

### ISSUE THREAD

**Issue by Junroot** [woowacourse-teams/2021-babble#96]
- [x] #98
- [x] 방 목록 페이지 내부 컴포넌트 마크업
- [x] #41 

- [x] #222
  - 방 목록 데이터 필요(방 id, 태그, 방장 정보 등)
- [ ] Lazy Loading 적용
- [x] #220
  - 자동완성 태그 검색 기능 
  - 자동완성에 필요한 태그 목록 데이터
- [x] 상단에 선택된 게임 이미지 보여주기
  - 선택된 게임에 해당되는 제목, 이미지 데이터

- [x] #223
  - 유저 프로필 설정하기, 보여주기
    - 유저 닉네임을 방 목록 페이지에서 미리 정해두고 방을 선택하면 해당 닉네임으로 바로 방 입장
    - 닉네임을 정해두지 않았다면 방 입장 시 입력 후 입장
    - page state에 랜덤 nickname(익명#94857483) 생성해서 가지고 있기
    - 기존 nickname이 닉네임 모달에 입력되어 있게 하기
    - default로 입력된 이름에 focus 처리(블럭 처리)하기
    - 변경하기 버튼 누르면 setState로 nickname 설정하면서 모달 닫기

- [x] #224  
  - 웹 소켓을 이용해서 채팅 connection/subscription/send 
  - 닉네임을 기존에 가지고있다가, 방 컴포넌트를 클릭하면 userId 생성 요청(post) 보내서 웹소켓 connect~send
- [x] #229

**Comment by iborymagic** [comment]
- 디자인 확정짓기: 1시간
- 컴포넌트 마크업: 4시간
- 페이지 마크업: 3시간
- 방 목록 보여주기: 2시간
- 자동완성 태그 검색 기능: 4시간
- 상단에 선택된 게임 이미지 보여주기: 30분
- 유저 프로필 설정하기, 보여주기: 3시간

**Comment by Junroot** [comment]
- API 설계: < 3시간. api하나당 40분 정도 걸릴 것으로 추정.
  - 방 목록: GET
  - 방 별 태그 목록: GET
  - 닉네임: POST
  - 방: POST (API 수정 필요. 인원 추가해야됨)
- API 구현: 6시간. API 하나당 넉넉하게 1.5시간

**Comment by Junroot** [comment]
> * API 설계: < 3시간. api하나당 40분 정도 걸릴 것으로 추정.
>   
>   * 방 목록: GET
>   * 방 별 태그 목록: GET
>   * 닉네임: POST
>   * 방: POST (API 수정 필요. 인원 추가해야됨)
> * API 구현: 6시간. API 하나당 넉넉하게 1.5시간
> * UX 디자인 및 마크업은 프론트의 의견에 �따름.

**Comment by Hyeon9mak** [comment]
API 설계: 3시간. rest api 설계는 그리 오래 걸리지 않을 것 같으나, 이미지 경로를 되돌려주는 등의 설계에 시간을 많이 잡아먹힐 것 같음.
API 구현: (테스트코드 작성 포함) 3시간 예상.

총 6시간

**Comment by lns13301** [comment]
방 목록 페이지 내부 컴포넌트 마크업 : 4시간

 방 목록 보여주기 : 1시간

방 목록 데이터 필요(방 id, 태그, 방장 정보 등) : 2시간

자동완성에 필요한 태그 목록 데이터 : 1시간

선택된 게임에 해당되는 제목, 이미지 데이터 : 2시간
 유저 프로필 설정하기, 보여주기

**Comment by unluckyjung** [comment]
방 목록에 노출에 필요한 정보가 프론트에서 무엇들을 요구할지가 관건

![image](https://user-images.githubusercontent.com/43930419/126266307-0e2be0bd-e384-499b-a4ad-87a498b49693.png)

피그마에 따르면, 
방에 존재하는 호스트 닉네임 + 태그 목록정도만 GET요청에 의한 응답으로 보내주면 될것으로 추정되어짐.

태그 검색시에는 또 서버에서 요청을 해서 LIST를 갱신해줄지에 대한 토의가 필요해보임
사례1) 클라이언트에서 처리 
- 일단 모든 방정보를 GET으로 받아감
- 태그가 걸리면 클라이언트에서 필터링

사례2) 서버에서 처리
- 태그검색창에서 태그가 추가될떄마다 클라이언트에서 GET (선택한 태그 목록(2시간, 실버), 태그목록) 요청
- 서버측에서 받아서 필터링한뒤 방목록 LIST를 반환
- 서버에 대한 부담이 좀 있지 않을까 우려되어짐.

개인적으로 서버측에서 주기적으로 갱신시키보다는, 이부분은 새로고침 버튼이 있어서 그떄마다 GET을 다시하는게 좋아보임.

**Comment by unluckyjung** [comment]
API 설계 : 1시간 ~ 1시간 30분 내외 
- 호스트정보 + 태그리스트만 요구할시에는 더 짧아질 수 있음.
- 하지만 인원 제한수 , 현재 들어가있는 인원수 등등의 추가적인 API 설계, 논의가 필요하다면 시간이 좀 소요될것으로 예상되어짐

구현 : 2시간 ~ 3시간내외 예상

**Comment by Hyeon9mak** [comment]
## 결론
6시간 정도 소요될 것으로 예상됨

**Comment by Junroot** [comment]
- [ ] 방 목록 조회 API 구현
