### ISSUE TITLE
GA(구글 애널리틱스) 를 도입하여 트래픽을 추적하고 수집한다.

### ISSUE THREAD

**Issue by lns13301** [woowacourse-teams/2021-babble#99]

**Comment by unluckyjung** [comment]
호스트 이름 관련 이슈 : https://www.notion.so/2b1882670e2543249975daaea29c1313

**Comment by unluckyjung** [comment]
![image](https://user-images.githubusercontent.com/43930419/133201765-ece37d72-19bf-4b78-97eb-ed342cce44d1.png)
![image](https://user-images.githubusercontent.com/43930419/133201808-fd8024ce-2a86-4a1c-8cc1-d2eaa410c838.png)
